# Generated by Django 4.1.1 on 2022-09-26 19:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_alter_city_name_alter_porofile_city'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Porofile',
            new_name='Profile',
        ),
    ]
