# Generated by Django 4.1.1 on 2022-09-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_job_aplication_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_aplication',
            name='cover_letter',
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
